<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.wildfly.redis</groupId>
        <artifactId>redis-client-feature-pack-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>redis-client-example</artifactId>
    <packaging>war</packaging>
    <name>Redis Client Example Application</name>

    <dependencies>
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>redis-client-injection</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>redis-example</finalName>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.wildfly.plugins</groupId>
                    <artifactId>wildfly-maven-plugin</artifactId>
                    <configuration>
                        <feature-packs>
                            <feature-pack>
                                <groupId>org.wildfly</groupId>
                                <artifactId>wildfly-galleon-pack</artifactId>
                                <version>${version.org.wildfly}</version>
                            </feature-pack>
                            <feature-pack>
                                <groupId>${project.groupId}</groupId>
                                <artifactId>redis-client-feature-pack</artifactId>
                                <version>${project.version}</version>
                            </feature-pack>
                        </feature-packs>
                        <layers>
                            <layer>jaxrs-server</layer>
                            <layer>redis-client</layer>
                            <layer>redis-web-clustering</layer>
                        </layers>
                        <packagingScripts>
                            <packaging-script>
                                <commands>
                                    <command>/subsystem=distributable-web/redis-session-management=redis:add(redis-connection=default,granularity=SESSION)</command>
                                    <command>/subsystem=distributable-web/redis-session-management=redis/affinity=none:add()</command>
                                    <command>/subsystem=distributable-web:write-attribute(name=default-session-management,value=redis)</command>
                                    <command>/subsystem=distributable-web/redis-single-sign-on-management=redis:add(redis-connection=default)</command>
                                    <command>/subsystem=distributable-web:write-attribute(name=default-single-sign-on-management,value=redis)</command>
                                </commands>
                            </packaging-script>
                        </packagingScripts>
                        <stability>community</stability>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-maven-plugin</artifactId>
                <executions>
                    <!-- Default instance to use with "mvn wildfly:dev": wildfly-maven-plugin takes care of deploying the application -->
                    <execution>
                        <id>provision-default-server</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration combine.children="merge">
                            <skipDeployment>true</skipDeployment>
                        </configuration>
                    </execution>
                    <!-- Instances to demonstrate session management: they come with the application pre-installed -->
                    <execution>
                        <id>provision-server-1</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration combine.children="merge">
                            <provisioning-dir>${project.build.directory}/server-1</provisioning-dir>
                        </configuration>
                    </execution>
                    <execution>
                        <id>provision-server-2</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration combine.children="merge">
                            <provisioning-dir>${project.build.directory}/server-2</provisioning-dir>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
